version: '3.8'

services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0.80-jre11
    volumes:
      - ./SmartCalc4/target/SmartCalc4.war:/usr/local/tomcat/webapps/SmartCalc4.war
      - ./SmartCalc4/src/cppSmartCalc/libsmartcalc.so:/usr/local/tomcat/native-jni-lib/libsmartcalc.so

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tomcat
    links:
      - tomcat
