/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calc_models_CalcModelJNI */

#ifndef _Included_calc_models_CalcModelJNI
#define _Included_calc_models_CalcModelJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calc_models_CalcModelJNI
 * Method:    calcResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_calc_models_CalcModelJNI_calcResult
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     calc_models_CalcModelJNI
 * Method:    calcGraphData
 * Signature: (Ljava/lang/String;DD)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_calc_models_CalcModelJNI_calcGraphData
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
